//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdryden.cflapi.v1.ModelTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdryden.cflapi.v1.ModelTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;game_id&quot;:2266,&quot;date_start&quot;:&quot;2015-11-29T17:00:00-05:00&quot;,&quot;game_number&quot;:95,&quot;week&quot;:23,&quot;season&quot;:2015,&quot;attendance&quot;:36634,&quot;event_type&quot;:{&quot;event_type_id&quot;:3,&quot;name&quot;:&quot;Grey Cup&quot;},&quot;event_status&quot;:{&quot;event_status_id&quot;:4,&quot;name&quot;:&quot;Final&quot;,&quot;is_active&quot;:false,&quot;quarter&quot;:4,&quot;minutes&quot;:0,&quot;seconds&quot;:1,&quot;down&quot;:2,&quot;yards_to_go&quot;:21},&quot;venue&quot;:{&quot;venue_id&quot;:9,&quot;name&quot;:&quot;Investors Group Field&quot;},&quot;weather&quot;:{&quot;temperature&quot;:-5,&quot;sky&quot;:&quot;Clear&quot;,&quot;wind_speed&quot;:&quot;&quot;,&quot;wind_direction&quot;:&quot;15 kmh from south&quot;,&quot;field_conditions&quot;:&quot;Dry field&quot;},&quot;coin_toss&quot;:{&quot;coin_tos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game2266 {
            get {
                return ResourceManager.GetString("Game2266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:87742,&quot;first_name&quot;:&quot;Rahim&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;ABDULLAH&quot;,&quot;birth_date&quot;:&quot;1976-03-22&quot;,&quot;birth_place&quot;:&quot;Jacksonville, Florida&quot;,&quot;height&quot;:6.06,&quot;weight&quot;:250,&quot;rookie_year&quot;:2002,&quot;foreign_player&quot;:true,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/r\/rahim-abdullah-87742.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:122,&quot;name&quot;:&quot;Clemson&quot;},&quot;position&quot;:{&quot;position_id&quot;:13,&quot;offence_defence_or_special&quot;:&quot;D&quot;,&quot;abbreviation&quot;:&quot;DL&quot;,&quot;description&quot;:&quot;Defensive Lineman&quot;},&quot;team&quot;:{&quot;is_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player87742 {
            get {
                return ResourceManager.GetString("Player87742", resourceCulture);
            }
        }
    }
}
