//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdryden.cflapi.v1.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdryden.cflapi.v1.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;game_id&quot;:2266,&quot;date_start&quot;:&quot;2015-11-29T17:00:00-05:00&quot;,&quot;game_number&quot;:95,&quot;week&quot;:23,&quot;season&quot;:2015,&quot;attendance&quot;:36634,&quot;event_type&quot;:{&quot;event_type_id&quot;:3,&quot;name&quot;:&quot;Grey Cup&quot;},&quot;event_status&quot;:{&quot;event_status_id&quot;:4,&quot;name&quot;:&quot;Final&quot;,&quot;is_active&quot;:false,&quot;quarter&quot;:4,&quot;minutes&quot;:0,&quot;seconds&quot;:1,&quot;down&quot;:2,&quot;yards_to_go&quot;:21},&quot;venue&quot;:{&quot;venue_id&quot;:9,&quot;name&quot;:&quot;Investors Group Field&quot;},&quot;weather&quot;:{&quot;temperature&quot;:-5,&quot;sky&quot;:&quot;Clear&quot;,&quot;wind_speed&quot;:&quot;&quot;,&quot;wind_direction&quot;:&quot;15 kmh from south&quot;,&quot;field_conditions&quot;:&quot;Dry field&quot;},&quot;coin_toss&quot;:{&quot;coin_tos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game2266 {
            get {
                return ResourceManager.GetString("Game2266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:148766,&quot;first_name&quot;:&quot;Odell&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;WILLIS&quot;,&quot;birth_date&quot;:&quot;1984-12-28&quot;,&quot;birth_place&quot;:&quot;Meridian, Mississippi&quot;,&quot;height&quot;:6.02,&quot;weight&quot;:265,&quot;rookie_year&quot;:2009,&quot;foreign_player&quot;:true,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/o\/odell-willis-148766.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:729,&quot;name&quot;:&quot;West Georgia&quot;},&quot;position&quot;:{&quot;position_id&quot;:13,&quot;offence_defence_or_special&quot;:&quot;D&quot;,&quot;abbreviation&quot;:&quot;DL&quot;,&quot;description&quot;:&quot;Defensive Lineman&quot;},&quot;team&quot;:{&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerDefensiveLine {
            get {
                return ResourceManager.GetString("PlayerDefensiveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:159141,&quot;first_name&quot;:&quot;Anthony&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;ALIX&quot;,&quot;birth_date&quot;:&quot;1986-08-12&quot;,&quot;birth_place&quot;:&quot;Saint-Vallier, France&quot;,&quot;height&quot;:6,&quot;weight&quot;:187,&quot;rookie_year&quot;:2012,&quot;foreign_player&quot;:false,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/a\/anthony-alix-159141.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:616,&quot;name&quot;:&quot;St. Francis Xavier&quot;},&quot;position&quot;:{&quot;position_id&quot;:16,&quot;offence_defence_or_special&quot;:&quot;S&quot;,&quot;abbreviation&quot;:&quot;K&quot;,&quot;description&quot;:&quot;Kicker&quot;},&quot;team&quot;:{&quot;is_set&quot;:t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerKicker {
            get {
                return ResourceManager.GetString("PlayerKicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:127305,&quot;first_name&quot;:&quot;Brian&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;CLAYBOURN&quot;,&quot;birth_date&quot;:&quot;1981-10-21&quot;,&quot;birth_place&quot;:&quot;Evansville, Indiana&quot;,&quot;height&quot;:6.01,&quot;weight&quot;:185,&quot;rookie_year&quot;:2006,&quot;foreign_player&quot;:true,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/b\/brian-claybourn-127305.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:739,&quot;name&quot;:&quot;Western  Kentucky&quot;},&quot;position&quot;:{&quot;position_id&quot;:14,&quot;offence_defence_or_special&quot;:&quot;S&quot;,&quot;abbreviation&quot;:&quot;P&quot;,&quot;description&quot;:&quot;Punter&quot;},&quot;team&quot;:{&quot;is_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerPunter {
            get {
                return ResourceManager.GetString("PlayerPunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:15850,&quot;first_name&quot;:&quot;Henry&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;BURRIS&quot;,&quot;birth_date&quot;:&quot;1975-05-04&quot;,&quot;birth_place&quot;:&quot;Spiro, Oklahoma&quot;,&quot;height&quot;:6.01,&quot;weight&quot;:190,&quot;rookie_year&quot;:1997,&quot;foreign_player&quot;:true,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/h\/henry-burris-15850.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:632,&quot;name&quot;:&quot;Temple&quot;},&quot;position&quot;:{&quot;position_id&quot;:1,&quot;offence_defence_or_special&quot;:&quot;O&quot;,&quot;abbreviation&quot;:&quot;QB&quot;,&quot;description&quot;:&quot;Quarterback&quot;},&quot;team&quot;:{&quot;is_set&quot;:true,&quot;team_id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerQuarterback {
            get {
                return ResourceManager.GetString("PlayerQuarterback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:80119,&quot;first_name&quot;:&quot;Raymonn&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;ADAMS&quot;,&quot;birth_date&quot;:&quot;1978-10-23&quot;,&quot;birth_place&quot;:&quot;Long Beach, California&quot;,&quot;height&quot;:6,&quot;weight&quot;:207,&quot;rookie_year&quot;:2002,&quot;foreign_player&quot;:true,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/r\/raymonn-adams-80119.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:157,&quot;name&quot;:&quot;Doane College&quot;},&quot;position&quot;:{&quot;position_id&quot;:2,&quot;offence_defence_or_special&quot;:&quot;O&quot;,&quot;abbreviation&quot;:&quot;RB&quot;,&quot;description&quot;:&quot;Running Back&quot;},&quot;team&quot;:{&quot;is_set&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerRunningBack {
            get {
                return ResourceManager.GetString("PlayerRunningBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;cfl_central_id&quot;:117995,&quot;first_name&quot;:&quot;T.J.&quot;,&quot;middle_name&quot;:&quot;&quot;,&quot;last_name&quot;:&quot;ACREE&quot;,&quot;birth_date&quot;:&quot;1982-07-21&quot;,&quot;birth_place&quot;:&quot;Pocatello, Idaho&quot;,&quot;height&quot;:5.11,&quot;weight&quot;:174,&quot;rookie_year&quot;:2005,&quot;foreign_player&quot;:true,&quot;image_url&quot;:&quot;http:\/\/d3ham790trbkqy.cloudfront.net\/wp-content\/uploads\/players\/t\/t-j--acree-117995.png&quot;,&quot;school&quot;:{&quot;school_id&quot;:55,&quot;name&quot;:&quot;Boise State&quot;},&quot;position&quot;:{&quot;position_id&quot;:8,&quot;offence_defence_or_special&quot;:&quot;O&quot;,&quot;abbreviation&quot;:&quot;WR&quot;,&quot;description&quot;:&quot;Wide Receiver&quot;},&quot;team&quot;:{&quot;is_set&quot;:true,&quot;tea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerWideReceiver {
            get {
                return ResourceManager.GetString("PlayerWideReceiver", resourceCulture);
            }
        }
    }
}
